# Generated by Django 5.0.3 on 2024-04-08 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='部门')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('sex', models.SmallIntegerField(choices=[(1, '女'), (0, '男')], verbose_name='性别')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='基础工资')),
                ('degree', models.CharField(max_length=8, verbose_name='学历')),
                ('marriage', models.SmallIntegerField(choices=[(0, '未婚'), (1, '已婚')], verbose_name='性别')),
                ('create_time', models.DateTimeField(verbose_name='入职时间')),
                ('jobtitle', models.CharField(max_length=8, verbose_name='职称')),
                ('post', models.CharField(max_length=16, verbose_name='岗位')),
                ('condition', models.SmallIntegerField(choices=[(1, '辞职'), (3, '退休'), (0, '在职'), (4, '转出'), (2, '辞退')], verbose_name='状态')),
                ('depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.department')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.IntegerField(verbose_name='奖金')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.userinfo')),
            ],
            options={
                'db_table': 'rewards',
            },
        ),
        migrations.CreateModel(
            name='Punishments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punishment', models.IntegerField(verbose_name='罚款')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.userinfo')),
            ],
            options={
                'db_table': 'punishments',
            },
        ),
    ]
