# Generated by Django 5.0.3 on 2024-04-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='condition',
            field=models.SmallIntegerField(choices=[(0, '在职'), (4, '转出'), (1, '辞职'), (2, '辞退'), (3, '退休')], verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别'),
        ),
    ]
